baseURL = "https://blog.frieserlabs.dev/"
languageCode = "en-us"
title = "Frieserlabs blog"
theme = "github.com/frieserlabs/hugo-theme-novela"
publishDir = "docs"

disqusShortname = "blog-frieserlabs-dev"
googleAnalytics = "G-6CE2P4EWF8"

[params]
description = "Blog for notes and ideas about software development and devops"

[module]
[[module.imports]]
path = "github.com/frieserlabs/hugo-theme-novela"

[social]
github = "https://github.com/frieser"
linkedin = "https://www.linkedin.com/in/hectormolano/"

[caches]
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "24h"
[caches.getcsv]
dir = ":cacheDir/:project"
maxAge = "24h"
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "24h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "24h"
[caches.modules]
dir = ":cacheDir/modules"
maxAge = "24h"